export declare const CONFIG_FILE_NAME = "adios.config.json";
export declare const SRC_DIR_STATIC = "statics";
export declare const SRC_DIR_LAYOUT = "layout";
export declare const SOURCE_ROOT = "source";
export declare const ASSETS_ROOT = "assets";
export declare const SOURCE_DIR_POSTS = "_posts";
export declare const SOURCE_DIR_ABOUT = "_about";
export declare const SOURCE_DIR_EXTRA = "_extra";
export declare const DST_DIR_ROOT = "public";
export declare const DST_DIR_ASSETS = "assets";
export declare const DST_DIR_STATIC = "statics";
export declare const DST_PAGE_POSTS = "posts";
export declare const DST_PAGE_INDEX_LIST = "list";
export declare const DST_PAGE_CATEGORIES = "categories";
export declare const DST_PAGE_TAGS = "tags";
export declare const DST_PAGE_EXTRA = "extra";
export declare const DST_PAGE_ABOUT = "about";
export declare const PAGE_TPL_NAME: {
    home: string;
    homeList: string;
    categories: string;
    categoryList: string;
    tags: string;
    tagList: string;
    about: string;
    posts: string;
    post: string;
    extra: string;
};
export declare const IP_REG: RegExp;
export declare const SLASH_REG: RegExp;
